/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package konwerterbajtow;

import java.awt.Color;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author Jędrzej
 */
public class EdytorPlikowUI extends javax.swing.JFrame {
    String dir;
    String extension;
    byte[] stream1;
    byte[] stream2;
    private List<Byte> stream1List = new ArrayList<Byte>();
    private List<Byte> stream2List = new ArrayList<Byte>();
//    na poczatku deklarowane jako false, ale przy kazdym kliknieciu będzie się zmieniało na wartosc przeciwna
    boolean textWritten = false;
    /**
     * Creates new form EdytorPlikowUI
     */
    public EdytorPlikowUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextFieldPath = new javax.swing.JTextField();
        TextFieldStream1 = new javax.swing.JTextField();
        TextFieldStream2 = new javax.swing.JTextField();
        TextFieldExtension = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ProcessButton = new javax.swing.JButton();
        BrowseButton = new javax.swing.JButton();
        InfoTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Int2TextField = new javax.swing.JTextField();
        textCheck = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 102));

        TextFieldPath.setText("C:\\Users\\User\\Desktop\\Studia\\jaInformatyk\\katalogProbny");

        TextFieldStream1.setText("55,88,99");

        TextFieldStream2.setText("78,45,12,65");
        TextFieldStream2.setToolTipText("");

        TextFieldExtension.setText(".txt");

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel1.setText("Poszukiwany ciąg bajtów do usunięcia");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel2.setText("Ciąg bajtów do wpisania");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel3.setText("Ścieżka dostępu do katalogu, który należy przeszukać");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel4.setText("Rozszerzenie pliku (z kropką np. \".txt\")");

        ProcessButton.setBackground(new java.awt.Color(51, 153, 0));
        ProcessButton.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        ProcessButton.setText("URUCHOM");
        ProcessButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcessButtonActionPerformed(evt);
            }
        });

        BrowseButton.setBackground(new java.awt.Color(51, 153, 0));
        BrowseButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        BrowseButton.setText("szukaj");
        BrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel5.setText("komunikat:");

        textCheck.setText("Tekst");
        textCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(TextFieldExtension, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(textCheck))
                                .addComponent(TextFieldPath, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Int2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BrowseButton)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(InfoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(TextFieldStream2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addComponent(ProcessButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(TextFieldStream1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TextFieldPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BrowseButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextFieldExtension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldStream1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Int2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextFieldStream2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(ProcessButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(InfoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


     
    private void ProcessButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcessButtonActionPerformed
        
        try {
//            if(this.Int1TextField.getText().equals("")){
//                stream1 = this.TextFieldStream1.getText().getBytes();
//                  
//            }
//            else{
//                String prepare = this.Int1TextField.getText().replaceAll("\\s", "");
//                
//                for(int i=0;i<prepare.length();i++){
//                    String x = prepare.substring(i, 1);
//                    if(!x.equals(",")){
//                        
//                        Byte w = x.getBytes();
//                    }
//                }
//            }
            
            if (textWritten){
                stream1 = this.TextFieldStream1.getText().getBytes();
                stream2 = this.TextFieldStream2.getText().getBytes();
                //      przejscie z primitive byte na listę Byte
                for(byte b : stream1){
                    stream1List.add(b);
                }
                for(byte b : stream2){
                    stream2List.add(b);
                }    
            }
            else{
                System.out.println("weszlo-----------------------");
                String temp1 = this.TextFieldStream1.getText();
                String[] temp1List = temp1.split(",");
                for(String s:temp1List){
                    byte b = Byte.valueOf(s);
                    stream1List.add(b);
                }
                String temp2 = this.TextFieldStream1.getText();
                String[] temp2List = temp2.split(",");
                for(String s:temp2List){
                    byte b = Byte.valueOf(s);
                    stream2List.add(b);
                }
            }
            for(byte b:stream1){
                System.out.println(b);
            }
            System.out.println("---");
            for(byte b:stream2){
                System.out.println(b);
            }
            Path path = Paths.get(TextFieldPath.getText());
            dir = path.toString();
            extension = this.TextFieldExtension.getText();
            
//            stworzenie kolejno dwoch obiektow, ktore wykonuja zadanie projektowe
            PrzeszukiwaczKatalogow katalog = new PrzeszukiwaczKatalogow(dir, extension);
            AnalizatorPlikow lista = new AnalizatorPlikow(katalog.getFiles(), stream1List, stream2List);
            this.InfoTextField.setText("Zakończono przeszukiwanie katalogu i zamieniono "+lista.getStringCounter()+" ciągów.");
        } 
        catch (IOException ex) {
            Logger.getLogger(EdytorPlikowUI.class.getName()).log(Level.SEVERE, null, ex);
        }
//        catch (NullPointerException ex) {
//            this.InfoTextField.setText("Podany katalog nie istnieje");
//        }
        catch(OutOfMemoryError e){
            System.out.println("OutOfMemoryError, przejście do alternatywnej metody konwersji");
            this.InfoTextField.setText("Wykryto za duży plik. Zamów wersję PREMIUM");
        }
    }//GEN-LAST:event_ProcessButtonActionPerformed

    private void BrowseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseButtonActionPerformed
        try{
            final JFileChooser fc = new JFileChooser();
            fc.setFileSelectionMode( JFileChooser.DIRECTORIES_ONLY);
            fc.showOpenDialog(this);     
            this.TextFieldPath.setText(fc.getSelectedFile().getPath());
        }
        catch(NullPointerException e){
//            zamknieto przeszukiwacz plikow bez wybrania katalogu
        }
    }//GEN-LAST:event_BrowseButtonActionPerformed

    private void textCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCheckActionPerformed
        textWritten = !textWritten;
        
    }//GEN-LAST:event_textCheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EdytorPlikowUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EdytorPlikowUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EdytorPlikowUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EdytorPlikowUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EdytorPlikowUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BrowseButton;
    private javax.swing.JTextField InfoTextField;
    private javax.swing.JTextField Int2TextField;
    private javax.swing.JButton ProcessButton;
    private javax.swing.JTextField TextFieldExtension;
    private javax.swing.JTextField TextFieldPath;
    private javax.swing.JTextField TextFieldStream1;
    private javax.swing.JTextField TextFieldStream2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JCheckBox textCheck;
    // End of variables declaration//GEN-END:variables
}
